import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, Check, CircleAlert, Database, Download, RotateCcw, Trash2, Upload } from 'lucide-react';
import './index.css';

const initialItems = [{ key: 'user:42', value: 'Amina Rahman' }, { key: 'product:18', value: 'Wireless headphones' }, { key: 'cart:91', value: '3 items' }];
function validUrl(value) { try { const url = new URL(value); return url.protocol === 'http:' || url.protocol === 'https:'; } catch { return false; } }

function App() {
  const [capacity, setCapacity] = useState(3); const [items, setItems] = useState(initialItems); const [key, setKey] = useState(''); const [value, setValue] = useState(''); const [logs, setLogs] = useState([{ text: 'Cache initialized', type: 'system' }]); const [repo, setRepo] = useState(''); const [file, setFile] = useState(null); const [error, setError] = useState(''); const [submitted, setSubmitted] = useState(false);
  function put() { if (!key.trim() || !value.trim()) { setError('Both key and value are required for PUT.'); return; } const next = items.filter(item => item.key !== key.trim()); next.unshift({ key: key.trim(), value: value.trim() }); const evicted = next.length > capacity ? next.pop() : null; setItems(next); setLogs([{ text: `PUT ${key.trim()}${evicted ? ` · evicted ${evicted.key}` : ''}`, type: 'put' }, ...logs].slice(0, 8)); setError(''); }
  function get() { const found = items.find(item => item.key === key.trim()); if (!found) { setLogs([{ text: `GET ${key.trim() || '(empty)'} · miss`, type: 'miss' }, ...logs].slice(0, 8)); setError(key.trim() ? 'Cache miss: that key is not currently stored.' : 'Enter a key to look it up.'); return; } setItems([found, ...items.filter(item => item.key !== found.key)]); setLogs([{ text: `GET ${found.key} · hit`, type: 'get' }, ...logs].slice(0, 8)); setError(''); }
  function clear() { setItems([]); setLogs([{ text: 'Cache cleared', type: 'system' }, ...logs].slice(0, 8)); setError(''); }
  function submit(event) { event.preventDefault(); const next = {}; if (!validUrl(repo)) next.repo = 'Enter a valid repository URL.'; if (!file) next.file = 'Upload a screenshot before submitting.'; setError(next.repo || next.file || ''); if (!Object.keys(next).length) setSubmitted(true); }
  function upload(event) { const selected = event.target.files?.[0]; if (!selected) return; if (!selected.type.startsWith('image/')) { setFile(null); setError('Only image files are accepted.'); return; } if (selected.size > 5 * 1024 * 1024) { setFile(null); setError('Please choose an image smaller than 5 MB.'); return; } setFile(selected); setError(''); }
  return <main className="min-h-screen px-4 py-8 sm:px-6 lg:py-12"><div className="mx-auto max-w-4xl"><header className="mb-7 flex items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-indigo-600">Task 02</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-ink sm:text-3xl">LRU cache playground</h1><p className="mt-1 text-sm text-slate-500">Explore recency, capacity, and eviction with live data.</p></div><span className="rounded-full bg-indigo-50 px-3 py-1.5 text-xs font-semibold text-indigo-700">Problem solving</span></header>
    <section className="grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-card sm:p-7"><div className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="rounded-lg bg-indigo-50 p-2 text-indigo-600"><Database size={19} /></div><div><h2 className="font-semibold">Cache state</h2><p className="text-xs text-slate-500">Most recently used appears first</p></div></div><button onClick={clear} className="rounded-lg p-2 text-slate-400 transition hover:bg-rose-50 hover:text-rose-600" aria-label="Clear cache"><Trash2 size={17} /></button></div><div className="mt-6 flex items-end justify-between gap-4"><label className="w-32 text-sm font-semibold text-slate-700">Capacity<input className="field" type="number" min="1" max="10" value={capacity} onChange={e => { const next = Math.max(1, Math.min(10, Number(e.target.value) || 1)); setCapacity(next); setItems(items.slice(0, next)); }} /></label><p className="pb-3 text-xs text-slate-500">{items.length} / {capacity} entries</p></div><div className="mt-5 space-y-3">{items.length ? items.map((item, index) => <div key={item.key} className="flex items-center justify-between gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3"><div className="flex min-w-0 items-center gap-3"><span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-xs font-bold ${index === 0 ? 'bg-indigo-600 text-white' : 'bg-white text-slate-500'}`}>{index + 1}</span><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-800">{item.key}</p><p className="truncate text-xs text-slate-500">{item.value}</p></div></div>{index === 0 && <span className="shrink-0 rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-emerald-700">MRU</span>}</div>) : <div className="rounded-xl border border-dashed border-slate-300 py-10 text-center text-sm text-slate-500">Your cache is empty.</div>}</div><div className="mt-6 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><input className="field mt-0" value={key} onChange={e => setKey(e.target.value)} placeholder="Key, e.g. user:42" aria-label="Cache key" /><input className="field mt-0" value={value} onChange={e => setValue(e.target.value)} placeholder="Value" aria-label="Cache value" /><div className="flex gap-2"><button className="primary" onClick={put}>PUT</button><button className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 hover:border-indigo-400 hover:text-indigo-700" onClick={get}>GET</button></div></div></div>
    <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-card sm:p-7"><div className="flex items-center gap-3"><div className="rounded-lg bg-emerald-50 p-2 text-emerald-600"><Activity size={19} /></div><div><h2 className="font-semibold">Operation history</h2><p className="text-xs text-slate-500">A small audit trail of cache activity</p></div></div><div className="mt-6 space-y-3">{logs.map((log, index) => <div key={`${log.text}-${index}`} className="flex gap-3 text-sm"><span className={`mt-1.5 h-2 w-2 shrink-0 rounded-full ${log.type === 'miss' ? 'bg-rose-400' : log.type === 'put' ? 'bg-indigo-500' : 'bg-emerald-500'}`} /><span className="text-slate-600">{log.text}</span></div>)}</div><div className="mt-7 rounded-xl bg-slate-50 p-4 text-xs leading-5 text-slate-500"><p className="font-semibold text-slate-700">How it works</p><p className="mt-1">Reads and writes move an item to the front. Once capacity is reached, the least recently used item at the end is evicted.</p></div></div></section>
    <form onSubmit={submit} className="mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-card sm:p-7"><div className="mb-5"><p className="text-xs font-semibold uppercase tracking-wider text-indigo-600">Submission</p><h2 className="mt-1 text-lg font-bold">Share your implementation</h2><p className="mt-1 text-sm text-slate-500">Add your repository and a screenshot of the working output.</p></div><label className="block text-sm font-semibold text-slate-700">GitHub repository URL<input className="field" value={repo} onChange={e => setRepo(e.target.value)} placeholder="https://github.com/you/repository" /></label><label className="mt-4 block text-sm font-semibold text-slate-700">Output screenshot<input className="mt-2 block w-full cursor-pointer rounded-lg border border-dashed border-slate-300 bg-slate-50 px-3 py-3 text-sm text-slate-500 file:mr-3 file:rounded-md file:border-0 file:bg-indigo-100 file:px-3 file:py-1.5 file:text-xs file:font-semibold file:text-indigo-700" type="file" accept="image/png,image/jpeg,image/webp" onChange={upload} />{file && <span className="mt-2 flex items-center gap-2 text-xs text-emerald-700"><Check size={14} />{file.name}</span>}</label>{error && <p className="mt-4 flex items-center gap-1 text-sm text-rose-600"><CircleAlert size={14} />{error}</p>}{submitted && <p className="mt-4 rounded-lg bg-emerald-50 px-3 py-2.5 text-sm font-medium text-emerald-700">Your repository and screenshot are ready for review.</p>}<button className="primary mt-5 w-full" type="submit">{submitted ? 'Update submission' : 'Mark task complete'} <Upload size={16} /></button></form>
  </div></main>;
}
createRoot(document.getElementById('root')).render(<App />);
